name: Publish Querier package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/querier/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v1
      name: checkout
    - uses: actions/setup-node@v1
      name: Install node.js
      with:
        node-version: '10.x'
    - run: npm install
      name: Install dependencies
      working-directory: packages/querier
    - run: npm run test:prod && npm run build
      name: Build
      working-directory: packages/querier
    - run: npm run semantic-release
      name: Publish
      working-directory: packages/querier
      env:
        GIT_AUTHOR_NAME: Uminily
        GIT_AUTHOR_EMAIL: uminily@gmail.com
        GIT_COMMITTER_NAME: Uminily
        GIT_COMMITTER_EMAIL: uminily@gmail.com
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_PUBLISH_TOKEN }}
